# Day-1 bootstrap at Corporate (Windows) — no AI assistant required.
param(
    [string]$Program = $env:PB_PROGRAM_ID,
    [string]$Hosts = $env:PB_ALLOWLIST_HOSTS,
    [string]$Classification = $(if ($env:PB_CLASSIFICATION) { $env:PB_CLASSIFICATION } else { "INTERNAL" }),
    [string]$IngestUrl = "",
    [switch]$NoSetup,
    [switch]$NoSap,
    [switch]$Yes
)

$ErrorActionPreference = "Continue"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
if (-not (Test-Path (Join-Path $Root "SETUP.cmd")) -and -not (Test-Path (Join-Path $Root "Install-PrivateBrain.ps1"))) {
    $Root = Split-Path -Parent $MyInvocation.MyCommand.Path
}

$CodexHome = if ($env:CODEX_HOME) { $env:CODEX_HOME } else { Join-Path $env:USERPROFILE ".codex" }
$BrainHome = if ($env:PRIVATE_BRAIN_HOME) { $env:PRIVATE_BRAIN_HOME } else { Join-Path $CodexHome "private-brain" }
$env:CODEX_HOME = $CodexHome
$env:PRIVATE_BRAIN_HOME = $BrainHome

Write-Host "=============================================="
Write-Host " Private Brain — START AT CORPORATE (Windows)"
Write-Host "=============================================="
Write-Host " CODEX_HOME=$CodexHome"
Write-Host " PRIVATE_BRAIN_HOME=$BrainHome"
Write-Host ""

$needSetup = -not (Test-Path (Join-Path $BrainHome "scripts\orchestrate.py"))
if (-not (Test-Path (Join-Path $CodexHome "hooks.json"))) { $needSetup = $true }

if ($needSetup -and -not $NoSetup) {
    Write-Host "==> Running SETUP / Install-PrivateBrain.ps1"
    $install = Join-Path $Root "Install-PrivateBrain.ps1"
    $setup = Join-Path $Root "SETUP.ps1"
    if (Test-Path $install) {
        & powershell -NoProfile -ExecutionPolicy Bypass -File $install
    } elseif (Test-Path $setup) {
        & powershell -NoProfile -ExecutionPolicy Bypass -File $setup
    } else {
        Write-Error "No Install-PrivateBrain.ps1 / SETUP.ps1 in $Root"
        exit 1
    }
} elseif ($needSetup) {
    Write-Error "Not installed and -NoSetup set"
    exit 1
}

if (-not $Yes) {
    if (-not $Program) {
        $Program = Read-Host "Program id (PB_PROGRAM_ID) [unassigned]"
        if (-not $Program) { $Program = "unassigned" }
    }
    if (-not $Hosts) {
        $Hosts = Read-Host "Allowlist hosts comma-separated (empty=any non-public)"
    }
    $c = Read-Host "Classification [$Classification]"
    if ($c) { $Classification = $c }
} else {
    if (-not $Program) { $Program = "unassigned" }
}

$env:PB_ENTERPRISE = "1"
$env:PB_PROGRAM_ID = $Program
$env:PB_CLASSIFICATION = $Classification
if ($Hosts) { $env:PB_ALLOWLIST_HOSTS = $Hosts }

$entYaml = Join-Path $BrainHome "config\enterprise.yaml"
if (Test-Path $entYaml) {
    Write-Host "==> Updating enterprise.yaml"
    $py = Join-Path $BrainHome "venv\Scripts\python.exe"
    if (-not (Test-Path $py)) { $py = (Get-Command python -ErrorAction SilentlyContinue).Source }
    if ($py) {
        $env:PROGRAM = $Program
        $env:CLASS = $Classification
        $env:HOSTS = $Hosts
        $env:ENT_YAML = $entYaml
        & $py -c @"
import os, re
from pathlib import Path
p = Path(os.environ['ENT_YAML'])
text = p.read_text(encoding='utf-8')
prog = os.environ.get('PROGRAM') or 'unassigned'
klass = os.environ.get('CLASS') or 'INTERNAL'
hosts = [h.strip() for h in (os.environ.get('HOSTS') or '').split(',') if h.strip()]
def set_scalar(key, val, text):
    import re
    pat = re.compile(rf'^{re.escape(key)}\s*:.*$', re.M)
    line = f'{key}: {val}'
    return pat.sub(line, text, count=1) if pat.search(text) else text + f'\n{line}\n'
text = set_scalar('program_id', prog, text)
text = set_scalar('default_classification', klass, text)
block = 'allowlist_hosts:\n' + (''.join(f'  - {h}\n' for h in hosts) if hosts else '  []\n')
if 'allowlist_hosts:' in text:
    text = re.sub(r'allowlist_hosts:\s*(?:\n(?:\s+-\s+.+)*)?', block, text, count=1)
else:
    text += '\n' + block
p.write_text(text, encoding='utf-8')
print('wrote', p)
"@
    }
}

$envFile = Join-Path $BrainHome "corporate.env.ps1"
@"
# Generated by start_at_corporate.ps1 — do not commit secrets
`$env:CODEX_HOME = '$CodexHome'
`$env:PRIVATE_BRAIN_HOME = '$BrainHome'
`$env:PB_ENTERPRISE = '1'
`$env:PB_PROGRAM_ID = '$Program'
`$env:PB_CLASSIFICATION = '$Classification'
$(if ($Hosts) { "`$env:PB_ALLOWLIST_HOSTS = '$Hosts'" } else { '' })
`$env:Path = "`$env:USERPROFILE\bin;" + `$env:Path
"@ | Set-Content -Path $envFile -Encoding UTF8
Write-Host "==> Wrote $envFile"

$bm = Join-Path $env:USERPROFILE "bin\beastMode.cmd"
if (-not (Test-Path $bm)) { $bm = Join-Path $BrainHome "scripts\beastMode.cmd" }
if (-not (Test-Path $bm)) { $bm = Join-Path $BrainHome "scripts\beastMode" }

Write-Host "==> Enterprise doctor"
& $bm --enterprise --doctor
if ($LASTEXITCODE -ne 0) {
    Write-Host "DOCTOR FAIL — fix issues, then re-run this script" -ForegroundColor Red
    exit $LASTEXITCODE
}

if ($IngestUrl) {
    Write-Host "==> Ingest $IngestUrl"
    & $bm --enterprise -ingestion $IngestUrl --ingest-only
}

if (-not $NoSap) {
    Write-Host "==> SAP pack"
    & $bm --enterprise --sap-pack
}

Write-Host ""
Write-Host " READY FOR PILOT" -ForegroundColor Green
Write-Host "  . $envFile"
Write-Host "  beastMode --enterprise"
Write-Host "  Program=$Program Class=$Classification"
Write-Host "  Read START_AT_CORPORATE.md"
exit 0
